name: test feature
on:
  push:
    branches: "feature/*"
jobs:
  test-qualidade:
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v4
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Unit tests
        run: mvn test
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: quangvo09/pull-request-action@v1
        with:
            branch_prefix: feature
            base_branch: develop
            labels: feature,develop
            assignees: quangvo09
            reviewers: quangvo09