name: Test develop

permissions:
  contents: write

on:
  pull_request:
    types: [opened, reopened]  # Aciona quando um PR é aberto ou reaberto
    branches: [master]  # Apenas para PRs que visam a branch integration

jobs:
  test-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests
        run: mvn test  # Altere conforme necessário para seu projeto

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Adicione seu token do SonarCloud aos Secrets do GitHub
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=duhhdm_api-irrigacao \
            -Dsonar.organization=duhhdm-1 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.qualityGate.wait=true  # Espera o resultado do Quality Gate

      - name: Check SonarCloud Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          STATUS=$(curl -s -u $SONAR_TOKEN: \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=duhhdm_api-irrigacao" | jq -r '.projectStatus.status')

          if [ "$STATUS" != "OK" ]; then
            echo "SonarCloud Quality Gate failed with status: $STATUS"
            exit 1  # Faz o workflow falhar
          fi