name: Test Feature and Create PR

permissions:
  contents: write

on:
  push:
    branches: "feature/*"

jobs:
  test-qualidade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Unit Tests
        run: mvn test

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Ou use MY_PAT se preferir
          title: 'Merge feature branch into develop'
          body: 'This PR is automatically created from the feature branch.'
          base: 'develop'
          head: ${{ github.ref }}  # A branch de origem do PR
