name: Deploy Develop

permissions:
  contents: write

on:
  pull_request:
    types: [ opened, reopened ]
    branches: [ integration ]

env:
  IMAGE_NAME: api-irrigacao
  AZURE_WEBAPP_NAME: web-port-ed
  ACR_NAME: ${{ secrets.LINK_REGISTRY }}  # Substitua pelo nome do seu ACR

jobs:
  test-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests
        run: mvn test

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=duhhdm_api-irrigacao \
            -Dsonar.organization=duhhdm-1 \
            -Dsonar.host.url=https://sonarcloud.io

  build:
    runs-on: ubuntu-latest
    needs: test-develop
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ env.ACR_NAME }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PROFILE_DEV }}
          images: '${{ env.ACR_NAME }}/${{ env.IMAGE_NAME }}:v3'
