name: test feature
on:
  push:
    branches: "feature/*"
jobs:
  test-qualidade:
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v4
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Unit tests
        run: mvn test
      - name: Create Pull Request
        if: success()  # Executa apenas se os testes forem bem-sucedidos
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}  # Token padrão do GitHub para ações
          title: 'Merge feature branch into develop'
          body: 'This PR is automatically created from the feature branch.'
          base: 'develop'  # Branch para onde o PR será direcionado
          head: ${{ github.ref }}  # A branch de origem do PR